language: java
services:
  - docker
script: 
  - docker build -t trondheimdc/submit-backend backend
  - docker build -t trondheimdc/submit-frontend frontend

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

